[package]
name = "hii"
version = "0.1.0"
description = "HII local-first visual interface"
authors = ["Ummi"]
edition = "2021"

[lib]
name = "hii_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
