[package]
name = "hii"
version = "0.1.0"
description = "HII local-first visual interface"
authors = ["Ummi"]
edition = "2021"
license-file = "../LICENSE"

[lib]
name = "hii_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["unstable", "protocol-asset"] }
hii-core = { path = "../crates/hii-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "5"

[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
