import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {EventEmitter} from 'node:events';
import {createAgentChats} from './chat-loop.mjs';
class Response extends EventEmitter {events=[];headersSent=false;destroyed=false;writableEnded=false;writeHead(){this.headersSent=true;}write(chunk){for(const line of chunk.split('\n'))if(line.startsWith('data: '))this.events.push(JSON.parse(line.slice(6)));}end(){this.writableEnded=true;}}
const deferred=()=>{let resolve;return {promise:new Promise(r=>resolve=r),resolve};};
async function fixture(t,fetchModel,runtime=async()=>({online:true,models:['local'],endpoint:'http://local'})){const directory=await mkdtemp(path.join(os.tmpdir(),'hii-chat-test-'));t.after(()=>rm(directory,{recursive:true,force:true}));return createAgentChats({directory,runtime,context:async()=>'',fetchModel});}
const body=(goal,chatId='chat')=>({goal,chatId,model:'local',device:'hii'});
const answer=text=>({ok:true,json:async()=>({choices:[{message:{content:JSON.stringify({action:'respond',text})}}]})});
test('concurrent admission serializes ordered turns before runtime resolves and preserves prior answer',async t=>{const runtimeGate=deferred(),first=deferred(),entered=deferred();let calls=0;const inputs=[];const chats=await fixture(t,async(_url,options)=>{inputs.push(JSON.parse(options.body).messages);if(++calls===1){entered.resolve();await first.promise;}return answer('answer '+calls);},async()=>{await runtimeGate.promise;return {online:true,models:['local'],endpoint:'http://local'};});const a=new Response(),b=new Response();const pa=chats.turn(body('first'),a),pb=chats.turn(body('second'),b);runtimeGate.resolve();await entered.promise;assert.equal(calls,1);first.resolve();await Promise.all([pa,pb]);assert.deepEqual((await chats.read('chat')).messages.map(m=>m.content),['first','answer 1','second','answer 2']);assert.equal(inputs[1].at(-2).content,'answer 1');assert.equal(b.events[0].type,'queued');assert.deepEqual((await chats.read('chat')).turns.map(t=>t.status),['completed','completed']);});
test('stop cancels queued messages promptly without releasing active executor or touching another chat',async t=>{const gate=deferred(),entered=deferred();let calls=0;const chats=await fixture(t,async(_url,{signal})=>{if(++calls===1){entered.resolve();await gate.promise;}if(signal.aborted)throw new DOMException('Stopped','AbortError');return answer('okay');});const running=chats.turn(body('first','one'),new Response());await entered.promise;const queued=chats.turn(body('cancel','two'),new Response());assert.equal(chats.stop('two'),true);await queued;const third=chats.turn(body('third','three'),new Response());await new Promise(r=>setTimeout(r,20));assert.equal(calls,1);gate.resolve();await Promise.all([running,third]);assert.equal((await chats.read('two')).turns[0].status,'stopped');assert.equal((await chats.read('one')).turns[0].status,'completed');});
test('model failure is recorded and next queued turn still executes',async t=>{let calls=0;const chats=await fixture(t,async()=>++calls===1?{ok:false,status:503}:answer('recovered'));const failed=new Response();await Promise.all([chats.turn(body('fails'),failed),chats.turn(body('next'),new Response())]);assert.equal(failed.events.at(-1).type,'error');assert.deepEqual((await chats.read('chat')).turns.map(t=>t.status),['failed','completed']);});
