import {readdir,open,stat} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
const home=os.homedir();let cache=null,stamp=0;const paths=new Map();
async function tail(file,bytes=1048576){const h=await open(file,'r');try{const s=await h.stat();const b=Buffer.alloc(Math.min(bytes,s.size));await h.read(b,0,b.length,Math.max(0,s.size-b.length));return b.toString('utf8');}finally{await h.close();}}
async function head(file,bytes=16384){const h=await open(file,'r');try{const b=Buffer.alloc(bytes);const {bytesRead}=await h.read(b,0,bytes,0);return b.subarray(0,bytesRead).toString('utf8');}finally{await h.close();}}
async function walk(dir,pattern,limit=3000){const out=[];async function visit(d,depth){if(depth>8||out.length>=limit)return;let entries;try{entries=await readdir(d,{withFileTypes:true});}catch{return;}entries.sort((a,b)=>b.name.localeCompare(a.name));for(const e of entries){if(out.length>=limit)break;const p=path.join(d,e.name);if(e.isDirectory()&&!['subagents','memory','blobs','quarantine'].includes(e.name))await visit(p,depth+1);else if(e.isFile()&&pattern.test(e.name))out.push(p);}}await visit(dir,0);return out;}
const parseLines=text=>text.split('\n').flatMap(l=>{try{return [JSON.parse(l)];}catch{return [];}});
export function redactText(value){return String(value).replace(/\b(sk-[A-Za-z0-9_-]{16,}|gh[pousr]_[A-Za-z0-9_]{16,})\b/g,'[redacted token]').replace(/((?:api[_ -]?key|access[_ -]?token|password|passcode|secret|token|key)\s*(?:[:=]|\bis\b)\s*)["']?[^\s,;"']+["']?/gi,'$1[redacted]');}
export function injectedText(text){return /^\s*(# AGENTS\.md instructions|<environment_context>|<INSTRUCTIONS>|<local-command|<system-reminder>|<session_context>|<command-name>|<command-message>|<task-notification>|<skill|Base directory for this skill:|You are an agent in a team)/i.test(text);}
export function messageText(record,source){let m=source==='Codex'&&record.type==='response_item'?record.payload:source==='Claude'&&!record.isMeta?record.message:null;if(source==='Generic')m=record;if(!m||!['user','assistant'].includes(m.role))return null;const text=typeof m.content==='string'?m.content:Array.isArray(m.content)?m.content.filter(x=>['text','input_text','output_text'].includes(x.type)).map(x=>x.text||'').join('\n'):'';if(!text||injectedText(text))return null;return {role:m.role,text:redactText(text.slice(0,20000))};}
export async function sessionList(){if(cache&&Date.now()-stamp<15000)return cache;const sessions=new Map();paths.clear();const add=(s,p)=>{s.title=injectedText(s.title)?s.source+' session':redactText(s.title);sessions.set(s.id,s);if(p)paths.set(s.id,p);};
 let index=[];try{index=parseLines(await tail(path.join(home,'.codex/session_index.jsonl'),4*1048576));}catch{}
 for(const r of index)if(r.id)add({id:'codex:'+r.id,source:'Codex',title:String(r.thread_name||'Codex session').slice(0,240),updatedAt:r.updated_at,status:'Unknown',readOnly:true});
 const codexFiles=[...await walk(path.join(home,'.codex/sessions'),/^rollout-.*\.jsonl$/),...await walk(path.join(home,'.codex/archived_sessions'),/^rollout-.*\.jsonl$/,1000)];
 for(const p of codexFiles){const id=p.match(/([a-f0-9]{8}-[a-f0-9-]{27})\.jsonl$/)?.[1];if(!id||!sessions.has('codex:'+id))continue;paths.set('codex:'+id,p);try{const prefix=await head(p);const match=prefix.match(/"cwd"\s*:\s*("(?:[^"\\]|\\.)*")/);sessions.get('codex:'+id).workspace=match?JSON.parse(match[1]):undefined;}catch{}}
 const claudeFiles=await walk(path.join(home,'.claude/projects'),/^[a-f0-9-]{36}\.jsonl$/);
 for(const p of claudeFiles){try{const rows=parseLines(await tail(p,65536));const messages=rows.map(r=>messageText(r,'Claude')).filter(Boolean);const id=path.basename(p,'.jsonl');const s=await stat(p);add({id:'claude:'+id,source:'Claude',title:(messages.find(m=>m.role==='user')?.text||'Claude session').slice(0,240),workspace:rows.findLast(r=>r.cwd)?.cwd,updatedAt:s.mtime.toISOString(),status:'Unknown',readOnly:true},p);}catch{}}
 const hiiFiles=await walk(path.join(home,'.hii/runs/cli'),/^receipt\.json$/);
 for(const p of hiiFiles){try{const r=JSON.parse(await tail(p,262144));add({id:'hii:'+r.id,source:'HII',title:String(r.goal||'HII run').slice(0,240),workspace:r.workspace,updatedAt:new Date(r.finished_at_unix_ms||r.created_at_unix_ms).toISOString(),status:r.status==='running'?'Unknown':r.status||'Unknown',readOnly:true},p);}catch{}}
 for(const [source,dir,pattern] of [['HII Chat',path.join(home,'.hii/chat/sessions'),/\.jsonl$/],['Gemini',path.join(home,'.gemini/tmp/ummi/chats'),/^session.*\.jsonl$/],['Hermes',path.join(home,'.hermes/sessions'),/^session.*\.json$/]]){
 for(const p of await walk(dir,pattern,1000)){try{const text=await tail(p,1048576);let rows=source==='Hermes'?[]:parseLines(text),doc=source==='Hermes'?JSON.parse(text):null;const messages=source==='Hermes'?(doc.messages||[]):source==='Gemini'?rows.flatMap(r=>r.$set?.messages||[]):[];const visible=messages.map(m=>messageText({...m,role:m.role||(m.type==='model'?'assistant':m.type)},'Generic')).filter(Boolean);const s=await stat(p);const key=source.toLowerCase().replace(' ','-')+':'+path.basename(p).replace(/\.jsonl?$/,'');add({id:key,source,title:(visible.find(m=>m.role==='user')?.text||source+' session').slice(0,240),workspace:rows.find(r=>r.coordinate)?.coordinate,updatedAt:s.mtime.toISOString(),status:'Unknown',readOnly:true},p);}catch{}}
 }
 cache=[...sessions.values()].sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))).slice(0,3000);stamp=Date.now();return cache;
}
export async function sessionDetail(id){const list=await sessionList();const session=list.find(s=>s.id===id);if(!session)return null;const p=paths.get(id);if(!p)return {session,messages:[],notice:'Transcript unavailable in the local session store.'};if(session.source==='HII'){const r=JSON.parse(await tail(p,262144));return {session,messages:[{role:'user',text:redactText(String(r.goal||'').slice(0,20000))},{role:'assistant',text:redactText(String(r.summary||'').slice(0,20000))}],notice:'Read-only HII goal and receipt summary.'};}if(['Hermes','Gemini','HII Chat'].includes(session.source)){const text=await tail(p);let messages=[];if(session.source==='Hermes'){try{messages=JSON.parse(text).messages||[];}catch{}}else if(session.source==='Gemini')messages=parseLines(text).flatMap(r=>r.$set?.messages||[]);return {session,messages:messages.map(m=>messageText({...m,role:m.role||(m.type==='model'?'assistant':m.type)},'Generic')).filter(Boolean).slice(-100),notice:session.source==='HII Chat'?'This HII session contains lifecycle records only; no conversation text is stored.':'Read-only local transcript excerpt. Tool output is omitted.'};}const rows=parseLines(await tail(p));return {session,messages:rows.map(r=>messageText(r,session.source)).filter(Boolean).slice(-100),notice:'Read-only local transcript excerpt. Tool output is omitted.'};}
