import {mkdir,readFile,writeFile,rename,rm,open,stat} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {randomUUID} from 'node:crypto';
import {sessionList,sessionDetail,redactText} from './session-sources.mjs';
export function createRegistry(root=path.join(os.homedir(),'.hii/agents/registry')){
 const snapshot=path.join(root,'snapshot.json'),lock=path.join(root,'write.lock');
 async function read(){try{return JSON.parse(await readFile(snapshot,'utf8'));}catch(e){if(e.code==='ENOENT')return {version:1,sessions:[],runs:[],updatedAt:null};throw e;}}
 async function mutate(fn){await mkdir(root,{recursive:true,mode:0o700});let handle;for(let n=0;n<100;n++){try{handle=await open(lock,'wx',0o600);await handle.writeFile(JSON.stringify({pid:process.pid}));break;}catch(e){if(e.code!=='EEXIST')throw e;try{if(Date.now()-(await stat(lock)).mtimeMs>30000){const owner=JSON.parse(await readFile(lock,'utf8'));try{process.kill(owner.pid,0);}catch(error){if(error.code==='ESRCH')await rm(lock);}}}catch{}await new Promise(r=>setTimeout(r,25));}}if(!handle)throw Error('HII agent registry is busy');try{const state=await read();const result=await fn(state);state.updatedAt=new Date().toISOString();const tmp=snapshot+'.'+randomUUID()+'.tmp';await writeFile(tmp,JSON.stringify(state),{mode:0o600});await rename(tmp,snapshot);return result;}finally{await handle.close();await rm(lock,{force:true});}}
 return {
 async sync(){const sessions=await sessionList();return mutate(s=>{s.sessions=sessions;return {sessions:sessions.length,sources:[...new Set(sessions.map(x=>x.source))],updatedAt:new Date().toISOString()};});},
 async sessions(filters={}){const s=await read();return s.sessions.filter(x=>(!filters.source||x.source.toLowerCase()===filters.source.toLowerCase())&&(!filters.workspace||x.workspace===filters.workspace)&&(!filters.query||[x.title,x.workspace,x.id].join(' ').toLowerCase().includes(filters.query.toLowerCase())));},
 async session(id){return sessionDetail(id);},
 async runs(){const s=await read();return [...s.runs,...s.sessions.filter(x=>x.source==='HII'&&!s.runs.some(r=>r.nativeRunId&&x.id==='hii:'+r.nativeRunId))].sort((a,b)=>String(b.updatedAt||b.startedAt).localeCompare(String(a.updatedAt||a.startedAt)));},
 async recordRun(run){if(typeof run.id!=='string'||!/^[a-zA-Z0-9:_-]{1,120}$/.test(run.id))throw Error('Invalid run id');return mutate(s=>{const existing=s.runs.find(r=>r.id===run.id);const safe={};for(const key of ['id','goal','model','workspace','status','startedAt','finishedAt','exitCode','nativeRunId','receiptPath','source','authority'])if(typeof run[key]==='string'||typeof run[key]==='number')safe[key]=typeof run[key]==='string'?redactText(run[key].slice(0,key==='goal'?20000:2000)):run[key];safe.updatedAt=new Date().toISOString();if(existing)Object.assign(existing,safe);else s.runs.unshift(safe);s.runs=s.runs.slice(0,3000);return existing||safe;});},
 async event(id,event){if(!/^[a-zA-Z0-9:_-]{1,120}$/.test(id))throw Error('Invalid run id');await mkdir(path.join(root,'events'),{recursive:true,mode:0o700});return mutate(async()=>{const file=path.join(root,'events',id+'.jsonl');let text='';try{text=await readFile(file,'utf8');}catch(e){if(e.code!=='ENOENT')throw e;}const clean=value=>typeof value==='string'?redactText(value):Array.isArray(value)?value.map(clean):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).filter(([k])=>!['messages','system','prompt','env','environment','input'].includes(k)).map(([k,v])=>[k,clean(v)])):value;const line=JSON.stringify(clean(event)).slice(0,65536);if(line.length>=65536)throw Error('Event exceeds registry limit');text+=line+'\n';if(text.length>2*1048576)text=text.slice(-1048576).split('\n').slice(1).join('\n');const tmp=file+'.tmp';await writeFile(tmp,text,{mode:0o600});await rename(tmp,file);});},
 async events(id){if(!/^[a-zA-Z0-9:_-]{1,120}$/.test(id))throw Error('Invalid run id');try{return (await readFile(path.join(root,'events',id+'.jsonl'),'utf8')).split('\n').flatMap(l=>{try{return [JSON.parse(l)];}catch{return [];}});}catch(e){if(e.code==='ENOENT')return [];throw e;}}
 };
}
export const registry=createRegistry();
export async function registryCommand(args){const [sub,id]=args;const option=name=>{const i=args.indexOf('--'+name);return i>=0?args[i+1]:undefined;};if(sub==='sync')return registry.sync();if(sub==='sessions')return registry.sessions({source:option('source'),workspace:option('workspace'),query:option('query')});if(sub==='session'){if(!id||id.startsWith('--'))throw Error('Session id required');return registry.session(id);}if(sub==='runs')return registry.runs();if(sub==='events'){if(!id||id.startsWith('--'))throw Error('Run id required');return registry.events(id);}throw Error('Unknown registry command');}
