<script lang="ts">
  import { onMount } from 'svelte';
  import HiiLogo from '$lib/components/HiiLogo.svelte';
  import TerminalPane from '$lib/components/TerminalPane.svelte';
  import BrowserPane from '$lib/components/workspace/BrowserPane.svelte';
  import ChatPane from '$lib/components/workspace/ChatPane.svelte';
  import SurfacePane from '$lib/components/workspace/SurfacePane.svelte';
  import StaticNode from '$lib/components/workspace/StaticNode.svelte';
  import type { PageData } from './$types';
  import type { WorkspaceDoc, WorkspaceNode, WorkspaceNodeType } from '@/lib/workspace/types';
  import { makeNode, seedFor, seedFromFile, seedFromString, seedsFromDataTransfer, type NodeSeed } from '@/lib/workspace/ingest';

  export let data: PageData;
  const surfaceCatalog = [
    { id:'knowledge', title:'Knowledge', path:'/knowledge', capabilityId:'hii.knowledge.workspace', detail:'canonical notes · systems · proof' },
    { id:'activate', title:'Activation', path:'/activate', capabilityId:'hii.agent.workspace_run', detail:'choose agent · approve context · run' },
    { id:'boards', title:'Boards', path:'/boards', capabilityId:'hii.board.task_kanban', detail:'bounded work · owners · blockers' },
    { id:'console', title:'Console', path:'/console', capabilityId:'hii.terminal.observe', detail:'agents · logs · receipts' },
    { id:'pilot', title:'Founder pilot', path:'/pilot', capabilityId:'hii.agent.workspace_run', detail:'one real task · one proved win' },
    { id:'dashboard', title:'Dashboard', path:'/dashboard', capabilityId:'hii.og.operational_graph', detail:'live control-plane overview' },
    { id:'termite', title:'Termite', path:'/termite', capabilityId:'termite.rhino.managed_job', detail:'Rhino jobs · evidence · receipts' },
    { id:'exchange', title:'Exchange', path:'/upload', capabilityId:'hii.exchange.asset_link', detail:'approved assets · controlled delivery' }
  ];
  let doc:WorkspaceDoc={version:1,updatedAt:new Date().toISOString(),viewport:{x:0,y:0,zoom:1},nextZ:1,nodes:[]};
  let ready=false; let selected:string|null=null; let omnibar=false; let query=''; let saveTimer:ReturnType<typeof setTimeout>|undefined;
  let context:any=null; let board:any[]=[]; let daemon:any=null; let canvas:HTMLElement; let mouse={x:400,y:300};
  $: commands=[
    ...surfaceCatalog.map(item=>['surface',`Open ${item.title}`,item.detail,item.path,item.capabilityId]),
    ['terminal','New terminal','zsh · run Claude or Codex'],['browser','New browser','URL or web search'],['chat','New HII chat','local context object'],['note','New note','persistent workspace object'],['context','Pin live system context','git · capabilities · next actions'],['board','Open board object','~/.hii board lanes'],['sound-field','Open South Berkeley sound field','modeled dBA']
  ].filter(item=>`${item[1]} ${item[2]}`.toLowerCase().includes(query.toLowerCase()));

  async function load(){ try{const response=await fetch('/api/workspace');if(response.ok)doc=await response.json();}finally{ready=true;} }
  function persist(){ if(saveTimer)clearTimeout(saveTimer); saveTimer=setTimeout(async()=>{doc.updatedAt=new Date().toISOString();await fetch('/api/workspace',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(doc)});},500); }
  function patch(id:string,patch:Partial<WorkspaceNode>){doc={...doc,nodes:doc.nodes.map(n=>n.id===id?{...n,...patch,updatedAt:new Date().toISOString()}:n)};persist();}
  function addSeeds(seeds:NodeSeed[],at:{x:number;y:number}){for(const [index,seed] of seeds.entries()){const node=makeNode(seed,at.x+index*28,at.y+index*28,++doc.nextZ);doc={...doc,nodes:[...doc.nodes,node]};selected=node.id}persist();}
  function spawn(type:string,payload:Record<string,unknown>={}){const seed=seedFor(type as WorkspaceNodeType,type==='browser'?{url:'https://duckduckgo.com',...payload}:type==='terminal'?{sessionId:crypto.randomUUID(),...payload}:payload);const center={x:(-doc.viewport.x+innerWidth/2)/doc.viewport.zoom,y:(-doc.viewport.y+innerHeight/2)/doc.viewport.zoom};addSeeds([seed],{x:center.x-seed.w/2,y:center.y-seed.h/2});omnibar=false;query='';if(type==='context')void refreshContext();if(type==='board')void refreshBoard();}
  function openSurface(id:string){const item=surfaceCatalog.find(candidate=>candidate.id===id);if(item)spawn('surface',{surface:item.id,title:item.title,path:item.path,capabilityId:item.capabilityId});}
  function close(id:string){doc={...doc,nodes:doc.nodes.filter(n=>n.id!==id)};selected=null;persist();}
  function select(node:WorkspaceNode){selected=node.id;if(node.z<doc.nextZ)patch(node.id,{z:++doc.nextZ});}
  function drag(event:PointerEvent,node:WorkspaceNode){if((event.target as HTMLElement).closest('button,input,textarea,iframe,a,.scroll,.xterm'))return;event.preventDefault();select(node);const sx=event.clientX,sy=event.clientY,ox=node.x,oy=node.y;const move=(e:PointerEvent)=>patch(node.id,{x:ox+(e.clientX-sx)/doc.viewport.zoom,y:oy+(e.clientY-sy)/doc.viewport.zoom});const up=()=>{removeEventListener('pointermove',move);removeEventListener('pointerup',up)};addEventListener('pointermove',move);addEventListener('pointerup',up);}
  function resize(event:PointerEvent,node:WorkspaceNode){event.preventDefault();event.stopPropagation();const sx=event.clientX,sy=event.clientY,ow=node.w,oh=node.h;const move=(e:PointerEvent)=>patch(node.id,{w:Math.max(140,ow+(e.clientX-sx)/doc.viewport.zoom),h:Math.max(80,oh+(e.clientY-sy)/doc.viewport.zoom)});const up=()=>{removeEventListener('pointermove',move);removeEventListener('pointerup',up)};addEventListener('pointermove',move);addEventListener('pointerup',up);}
  function pan(event:PointerEvent){if(event.target!==canvas)return;const sx=event.clientX,sy=event.clientY,ox=doc.viewport.x,oy=doc.viewport.y;const move=(e:PointerEvent)=>doc={...doc,viewport:{...doc.viewport,x:ox+e.clientX-sx,y:oy+e.clientY-sy}};const up=()=>{removeEventListener('pointermove',move);removeEventListener('pointerup',up);persist()};addEventListener('pointermove',move);addEventListener('pointerup',up);}
  function zoom(event:WheelEvent){if(!event.metaKey&&!event.ctrlKey)return;event.preventDefault();doc={...doc,viewport:{...doc.viewport,zoom:Math.min(2.5,Math.max(.25,doc.viewport.zoom*Math.exp(-event.deltaY*.002)))}};persist();}
  async function refreshContext(){try{context=await (await fetch('/api/context')).json()}catch{}}
  async function refreshBoard(){try{board=(await (await fetch('/api/board/tasks')).json()).tasks||[]}catch{}}
  async function refreshDaemon(){try{daemon=await (await fetch('/api/daemon')).json()}catch{}}
  function keydown(event:KeyboardEvent){if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();omnibar=!omnibar;}if(event.key==='Escape')omnibar=false;}
  async function drop(event:DragEvent){event.preventDefault();if(!event.dataTransfer)return;const at={x:(event.clientX-doc.viewport.x)/doc.viewport.zoom,y:(event.clientY-doc.viewport.y)/doc.viewport.zoom};addSeeds(await seedsFromDataTransfer(event.dataTransfer),at)}
  async function addFiles(files:File[]){const seeds=await Promise.all(files.map(seedFromFile));const center={x:(-doc.viewport.x+innerWidth/2)/doc.viewport.zoom,y:(-doc.viewport.y+innerHeight/2)/doc.viewport.zoom};addSeeds(seeds,{x:center.x-190,y:center.y-150})}
  onMount(()=>{load();refreshContext();refreshBoard();refreshDaemon();const move=(e:PointerEvent)=>mouse={x:e.clientX,y:e.clientY};const paste=(e:ClipboardEvent)=>{if((e.target as Element)?.closest?.('input,textarea,[contenteditable]'))return;const files=[...(e.clipboardData?.files||[])];if(files.length){e.preventDefault();void addFiles(files);return}const text=e.clipboardData?.getData('text/plain');if(text){const at={x:(mouse.x-doc.viewport.x)/doc.viewport.zoom,y:(mouse.y-doc.viewport.y)/doc.viewport.zoom};addSeeds([seedFromString(text)],at)}};window.addEventListener('keydown',keydown);window.addEventListener('pointermove',move);window.addEventListener('paste',paste);return()=>{window.removeEventListener('keydown',keydown);window.removeEventListener('pointermove',move);window.removeEventListener('paste',paste)}});
</script>

{#if !data.enabled}<div class="hii-page flex min-h-[60vh] flex-col items-center justify-center gap-3"><p class="hii-kicker">surface off</p><h1 class="hii-page-title">HII is turned off</h1></div>
{:else}<main bind:this={canvas} class="absolute inset-0 touch-none overflow-hidden" on:pointerdown={pan} on:wheel={zoom} on:dragover|preventDefault on:drop={drop} style="background:var(--hii-warm-white) radial-gradient(circle,rgba(23,23,23,.08) 1px,transparent 1px);background-size:32px 32px">
  <div class="absolute left-0 top-0 origin-top-left" style={`transform:translate(${doc.viewport.x}px,${doc.viewport.y}px) scale(${doc.viewport.zoom})`}>
    {#each doc.nodes as node (node.id)}<section role="group" aria-label={`${node.type} workspace node`} class="group absolute left-0 top-0 flex flex-col overflow-hidden rounded-lg bg-white" class:ring-1={selected===node.id} on:pointerdown={(event)=>drag(event,node)} style={`transform:translate(${node.x}px,${node.y}px);width:${node.w}px;height:${node.h}px;z-index:${Math.round(node.z)};box-shadow:0 4px 16px rgba(23,23,23,.08)`}>
      <header class="flex h-7 shrink-0 items-center justify-between border-b border-neutral-900/10 px-2.5"><span class="truncate font-mono text-[11px] lowercase tracking-wide text-neutral-500">{String(node.payload.title||node.type)}</span><button class="opacity-0 group-hover:opacity-100" on:click={()=>close(node.id)} aria-label="close node">×</button></header>
      <div class="relative min-h-0 flex-1">
        {#if ['note','text','canvas-text','ink','link','file','image','media','html','font'].includes(node.type)}<StaticNode {node} onPayload={(payload)=>patch(node.id,{payload:{...node.payload,...payload}})} />
        {:else if node.type==='terminal'}<TerminalPane sessionId={String(node.payload.sessionId)} cwd={String(node.payload.cwd||'')} />
        {:else if node.type==='browser'}<BrowserPane {node} onPayload={(payload)=>patch(node.id,{payload:{...node.payload,...payload}})} />
        {:else if node.type==='context'}<div class="scroll h-full overflow-auto p-3.5"><div class="flex justify-between font-mono text-[10px] uppercase text-neutral-400"><span>system context</span><button on:click={refreshContext}>refresh</button></div><div class="mt-3 rounded-md border p-3"><strong class="font-mono text-[11px]">{context?.git?.branch||'reading…'}</strong><p class="font-mono text-[10px] text-neutral-500">{context?.git?.status?.length||0} dirty paths</p></div><h3 class="mt-3 font-mono text-[10px] uppercase text-neutral-400">next</h3>{#each context?.nextActions?.slice(0,4)||[] as action}<p class="mt-1 text-[12px]"><span class="text-[var(--hii-electric-blue)]">{action.track}</span> {action.next}</p>{/each}</div>
        {:else if node.type==='board'}<div class="scroll h-full overflow-auto p-3.5"><div class="flex justify-between font-mono text-[10px] uppercase text-neutral-400"><span>board</span><a href="/boards">open ↗</a></div>{#each ['doing','next','blocked','backlog'] as lane}{#if board.some(task=>task.lane===lane)}<h3 class="mt-3 font-mono text-[10px] uppercase text-neutral-400">{lane}</h3>{#each board.filter(task=>task.lane===lane).slice(0,6) as task}<div class="mt-1.5 rounded-md border p-2 text-[12px]">{task.title}</div>{/each}{/if}{/each}</div>
        {:else if node.type==='surface'}<SurfacePane path={String(node.payload.path||'/')} title={String(node.payload.title||'HII surface')} />
        {:else if node.type==='chat'}<ChatPane {node} onPayload={(payload)=>patch(node.id,{payload:{...node.payload,...payload}})} />
        {:else if node.type==='sound-field'}<div class="relative h-full overflow-hidden bg-[#07131c] text-white"><div class="absolute inset-0 opacity-70" style="background:radial-gradient(circle at 65% 55%,#ffce3a 0,transparent 7%),radial-gradient(circle at 45% 40%,#ff6b35 0,transparent 14%),radial-gradient(circle at 50% 50%,#176bff 0,transparent 55%)"></div><div class="relative p-5"><p class="font-mono text-xs text-white/60">MODELED / WEEKDAY / 18:00</p><h2 class="mt-2 text-3xl">South Berkeley Sound Field</h2><p class="mt-3 max-w-sm text-sm text-white/70">A provenance-aware spatial scene. Replace modeled values with calibrated measurements before analysis.</p></div></div>
        {:else}<div class="grid h-full place-items-center p-4 font-mono text-[11px] text-neutral-400">{String(node.payload.text||node.payload.title||node.type)}</div>{/if}
      </div><button type="button" aria-label={`Resize ${node.type} node`} class="absolute bottom-0 right-0 h-4 w-4 cursor-nwse-resize" on:pointerdown={(event)=>resize(event,node)}></button>
    </section>{/each}
  </div>
  {#if ready&&doc.nodes.length===0}<div class="pointer-events-none absolute inset-0 grid place-items-center text-[13px] tracking-wide text-neutral-400">paste or drop media · ⌘K commands · ⌘scroll zoom</div>{/if}
  <div class="pointer-events-none absolute left-5 top-4 select-none"><HiiLogo className="h-4 w-auto" /></div>
  <div class="absolute left-4 top-12 z-50 flex w-11 flex-col items-center gap-1 rounded-[14px] bg-neutral-950 p-1.5 shadow-xl"><button class="grid h-8 w-8 place-items-center rounded-[9px] bg-[var(--hii-electric-blue)] text-white" on:click={()=>spawn('chat')} title="Chat">✦</button><label class="grid h-8 w-8 cursor-pointer place-items-center rounded-[9px] text-neutral-300 hover:bg-white/10" title="Add media">⊕<input type="file" multiple class="sr-only" on:change={(event)=>{void addFiles([...(event.currentTarget.files||[])]);event.currentTarget.value=''}}/></label><button class="grid h-8 w-8 place-items-center rounded-[9px] text-neutral-300 hover:bg-white/10" on:click={()=>spawn('canvas-text')} title="Canvas text">T</button></div>
  <div class="absolute bottom-5 left-1/2 flex -translate-x-1/2 gap-1 rounded-full bg-white px-3 py-2 shadow-lg"><button class="rounded-full bg-neutral-950 px-3 py-1 font-mono text-[11px] text-white" on:click={()=>openSurface('knowledge')}>knowledge</button><button class="rounded-full px-3 py-1 font-mono text-[11px]" on:click={()=>openSurface('activate')}>activate</button><button class="rounded-full px-3 py-1 font-mono text-[11px]" on:click={()=>openSurface('boards')}>boards</button><button class="rounded-full px-3 py-1 font-mono text-[11px]" on:click={()=>openSurface('console')}>console</button>{#each ['terminal','browser','note'] as type}<button class="rounded-full px-3 py-1 font-mono text-[11px]" on:click={()=>spawn(type)}>+ {type}</button>{/each}</div>
  <button class="absolute right-5 top-4 rounded-full bg-[var(--hii-electric-blue)] px-4 py-2 font-mono text-[11px] text-white shadow-lg" on:click={refreshDaemon}><i class="mr-2 inline-block h-2 w-2 rounded-full bg-[var(--hii-acid-green)]"></i>hiid {daemon?.instances?.length||context?.capabilities?.length||'…'}</button>
  {#if omnibar}<div class="absolute inset-0 z-50 bg-white/80 backdrop-blur-sm"><button type="button" class="absolute inset-0 cursor-default" aria-label="Close command palette" on:click={()=>omnibar=false}></button><div class="absolute left-1/2 top-1/2 w-[min(620px,90vw)] -translate-x-1/2 -translate-y-1/2 overflow-hidden rounded-2xl bg-white shadow-2xl" role="dialog" aria-modal="true" aria-label="Create workspace object"><div class="flex items-center gap-3 border-b p-4"><span>⌘</span><input bind:value={query} class="w-full outline-none" placeholder="Open a surface, create an object, or start work…" /></div><div class="max-h-[420px] overflow-auto p-2">{#each commands as command}<button class="flex w-full items-center gap-3 rounded-xl p-3 text-left hover:bg-neutral-50" on:click={()=>command[0]==='surface'?spawn('surface',{title:command[1].replace('Open ',''),path:command[3],capabilityId:command[4]}):spawn(command[0])}><span class="text-xl">{command[0]==='surface'?'↗':'+'}</span><span class="flex-1"><strong class="block">{command[1]}</strong><small class="text-neutral-400">{command[2]}</small></span><kbd class="font-mono text-[10px] text-neutral-400">{command[0]==='surface'?'open':'create'}</kbd></button>{/each}</div></div></div>{/if}
</main>{/if}
