<script lang="ts">
  import { onMount } from 'svelte';
  let {data}=$props();
  const install=['Download the Termite alpha package.','Unzip it and keep the release folder somewhere easy to find.','Install the Rhino bridge from the staged Yak/plugin contents.','Open or restart Rhino 8.','Run StartTermiteBridge in the Rhino command line.','Start the MCP server with EDIT_SAFE permission for geometry tests.','Run the doctor check and confirm rhino.ping passes.'];
  const update=['Download the newest alpha package from this page.','Quit Rhino 8 before replacing the bridge files.','Replace the prior Termite release folder with the new release folder.','Reinstall the Rhino bridge, then reopen Rhino.','Run StartTermiteBridge again after every update.','Run the doctor check before testing client geometry.'];
  const scale=['Managed alpha: you run Termite on this Mac for trusted clients and log every job in HII.','Provisioned install: HII guides a user through local setup with the installer manager.','Tracked service: each launch becomes a job with budget, status, logs, proof, and deliverables.','Fleet mode: AII can route jobs to a secure VPS, Mac worker, or client machine when demand grows.','Commerce layer: HII turns repeatable capability into subscriptions, pilots, items, and approved proof.'];
  let installer:any=$state(null), jobs:any[]=$state([]), workflow=$state('rhino-smoke-test'), budget=$state('alpha-free'), prompt=$state('Run a Termite alpha smoke test: connect to Rhino, inspect document state, create safe test geometry, capture a viewport proof, and report blockers.'), busy=$state(''), message=$state('');
  async function refresh(){try{const [i,j]=await Promise.all([fetch('/api/termite/installer'),data.signedIn?fetch('/api/termite/jobs'):Promise.resolve(null)]);installer=i.ok?await i.json():null;if(j&&j.ok)jobs=(await j.json()).jobs??[];}catch{message='Local installer status is unavailable.'}}
  async function run(actionId:string){busy=actionId;const res=await fetch('/api/termite/installer',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({actionId})}),payload=await res.json();if(res.ok)installer=payload;else message=payload.error??'Installer action failed.';busy='';}
  async function launch(){busy='launch';const res=await fetch('/api/termite/jobs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({workflow,prompt,budget})}),payload=await res.json();if(res.ok)jobs=[payload.job,...jobs];else message=payload.error??'Launch failed.';busy='';}
  onMount(refresh);
</script>
<div class="hii-page space-y-12"><section class="hii-page-header"><p class="hii-kicker">Termite alpha</p><h1 class="hii-page-title">Provisioned AI automation for Rhino 8.</h1><p class="hii-page-copy">Termite is the first HII capability item: a managed agent workflow that can inspect Rhino documents, create test geometry, capture proof, and turn the result into a tracked client job.</p><div class="mt-6 flex gap-3"><a href="/downloads/termite-alpha-macos.zip" class="hii-command-button">Download alpha zip</a><a href="/" class="hii-secondary-action">Back to HII</a></div><p class="mt-4 text-xs text-neutral-400">macOS alpha package · 373 KB · SHA-256 582dc87e1a59e3b6907d11675b2ea611b190ac14d3e98b695f4a7ad57f2dc70d</p></section>
{#each [['Install Sequence',install],['Update Sequence',update],['Scale Path',scale]] as group}<section><h2 class="text-xl font-semibold">{group[0]}</h2><ol class="mt-4 space-y-3">{#each group[1] as step}<li class="hii-card">{step}</li>{/each}</ol></section>{/each}
<section class="border-t border-[var(--hii-electric-blue)] pt-8"><div class="flex justify-between"><div><h2 class="text-xl font-semibold">Local LLM Install Manager</h2><p class="mt-2 text-sm text-neutral-600">HII checks the local Termite/Rhino install and runs only whitelisted install scripts.</p></div><button class="hii-secondary-action" onclick={refresh}>Refresh</button></div>{#if installer?.state}<div class="mt-5 grid gap-3 sm:grid-cols-2">{#each [['alphaZip','HII alpha zip exists'],['stagedRelease','Termite release staged'],['rhinoApp','Rhino 8 installed'],['rhinoPlugin','Termite Rhino bridge installed']] as row}<div class="hii-stat-card"><div class="text-xs uppercase text-neutral-500">{row[1]}</div><div class="mt-1 font-mono text-sm">{installer.state[row[0]]?'PASS':'MISSING'}</div></div>{/each}</div>{/if}<div class="hii-terminal-frame mt-5 p-4 font-mono text-sm"><p>$ local-llm installer-manager</p><p>model: {installer?.guidance?.model??'checking…'}</p><p>next: {installer?.guidance?.text??'Loading local installer guidance…'}</p></div><div class="mt-5 grid gap-3">{#each installer?.actions??[] as action}<button class="hii-card text-left" disabled={Boolean(busy)} onclick={()=>run(action.id)}><strong>{busy===action.id?'Running…':action.label}</strong><span class="mt-1 block text-sm text-neutral-500">{action.description}</span></button>{/each}</div></section>
<section class="border-t border-[var(--hii-electric-blue)] pt-8"><div class="flex justify-between"><div><h2 class="text-xl font-semibold">Managed Job Terminal</h2><p class="mt-2 text-sm text-neutral-600">Launch a quoted Termite job and return logs, proof, and a ledger-backed receipt.</p></div>{#if !data.signedIn}<a href="/login?next=/termite" class="hii-command-button">Sign in</a>{/if}</div><div class="hii-terminal-frame mt-5 p-4 font-mono text-sm"><p>$ hii termite launch --managed</p><p>status: {data.signedIn?'ready':'account required'}</p>{#if jobs[0]}<p>latest: {jobs[0].id} · {jobs[0].status}</p>{/if}</div><div class="mt-5 grid gap-4"><select bind:value={workflow} class="hii-select px-3 py-2" disabled={!data.signedIn}><option value="rhino-smoke-test">Rhino smoke test</option><option value="geometry-check">Geometry check</option><option value="viewport-proof">Viewport proof</option></select><select bind:value={budget} class="hii-select px-3 py-2" disabled={!data.signedIn}><option value="alpha-free">Alpha feedback run</option><option value="pilot-paid">Paid runner pilot</option></select><textarea bind:value={prompt} class="hii-textarea min-h-36 px-3 py-2" disabled={!data.signedIn}></textarea><button onclick={launch} disabled={!data.signedIn||Boolean(busy)} class="hii-command-button disabled:opacity-50">{busy==='launch'?'Launching…':'Launch managed job'}</button></div>{#if message}<p class="mt-3 text-sm text-red-600">{message}</p>{/if}</section></div>
