import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
import {createBridgeHandler} from './bridge-handler.mjs';
const packet=o=>Buffer.from(JSON.stringify({client:'client:owner',id:'turn',...o}));
test('bridge acknowledges request and ordered chunks and refuses premature end',async()=>{const events=[],bodies=[];const active=new Map();const handler=createBridgeHandler({active,send:e=>events.push(e),fetchLocal:async(_url,o)=>{bodies.push(o.body.toString());return {status:200,headers:new Headers(),body:(async function*(){yield Buffer.from('ok');})()};}});await handler(packet({t:'request',method:'POST',path:'/api/agent-chat',bodyBytes:4}));assert.equal(events.at(-1).t,'upload-ready');await handler(packet({t:'end'}));assert.equal(events.at(-1).message,'Upload incomplete.');assert.equal(bodies.length,0);await handler(packet({t:'request',method:'POST',path:'/api/agent-chat',bodyBytes:4}));await handler(packet({t:'upload',sequence:0,data:Buffer.from('test').toString('base64')}));assert.equal(events.at(-1).t,'upload-ack');await handler(packet({t:'end'}));assert.deepEqual(bodies,['test']);assert.equal(events.at(-1).t,'done');});
test('bridge rejects duplicate chunk and old protocol explicitly',async()=>{const events=[],active=new Map();const handler=createBridgeHandler({active,send:e=>events.push(e)});await handler(packet({t:'request',method:'POST',path:'/api/agent-chat'}));assert.match(events.at(-1).message,/Refresh/);await handler(packet({t:'request',method:'POST',path:'/api/agent-chat',bodyBytes:2}));await handler(packet({t:'upload',sequence:1,data:'YQ=='}));assert.match(events.at(-1).message,/sequence/);assert.equal(active.size,0);});
async function transport(t){const dom=new JSDOM('<html/>',{url:'https://hii.test',runScripts:'outside-only'});t.after(()=>dom.window.close());const w=dom.window,sent=[];class Socket{static OPEN=1;readyState=1;bufferedAmount=0;constructor(){Socket.instance=this;queueMicrotask(()=>this.onmessage({data:'{"t":"ready"}'}));}send(text){sent.push(JSON.parse(text));}close(){this.onclose?.();}receive(o){this.onmessage({data:JSON.stringify(o)});}}w.WebSocket=Socket;w.TextEncoder=TextEncoder;w.Response=Response;w.ReadableStream=ReadableStream;w.AbortController=AbortController;const source=(await readFile(new URL('./public/transport.js',import.meta.url),'utf8')).replace('export async function privateFetch','async function privateFetch');w.eval(source+'\nwindow.privateFetch=privateFetch;');return {w,sent,Socket};}
const tick=()=>new Promise(resolve=>setTimeout(resolve,0));
test('browser waits for each authenticated frame acknowledgment before end across simultaneous requests',async t=>{const {w,sent,Socket}=await transport(t);const a=w.privateFetch('/api/agent-chat',{method:'POST',body:'first'}),b=w.privateFetch('/api/agent-chat',{method:'POST',body:'second'});await tick();assert.deepEqual(sent.map(m=>m.t),['request','request']);const [one,two]=sent;Socket.instance.receive({t:'upload-ready',id:two.id});await tick();assert.equal(sent.at(-1).id,two.id);assert.equal(sent.at(-1).t,'upload');assert.equal(sent.some(m=>m.t==='end'),false);Socket.instance.receive({t:'upload-ack',id:two.id,sequence:0});await tick();assert.equal(sent.at(-1).t,'end');Socket.instance.receive({t:'upload-ready',id:one.id});await tick();Socket.instance.receive({t:'upload-ack',id:one.id,sequence:0});await tick();for(const request of [one,two]){Socket.instance.receive({t:'headers',id:request.id,status:200,contentType:'application/json'});Socket.instance.receive({t:'done',id:request.id});}await Promise.all([a,b]);});
test('operator abort while waiting for bridge acknowledgment rejects AbortError and never sends end',async t=>{const {w,sent}=await transport(t);const controller=new AbortController();const request=w.privateFetch('/api/agent-chat',{method:'POST',body:'cancel',signal:controller.signal});await tick();controller.abort();await assert.rejects(request,e=>e.name==='AbortError');await tick();assert.deepEqual(sent.map(m=>m.t),['request','cancel']);});
test('same request id from different clients keeps independent bodies and cancellation',async()=>{const events=[],bodies=[],active=new Map();const handler=createBridgeHandler({active,send:e=>events.push(e),fetchLocal:async(_url,o)=>{bodies.push(o.body.toString());return {status:200,headers:new Headers(),body:(async function*(){yield Buffer.from('ok');})()};}});const frame=(client,o)=>Buffer.from(JSON.stringify({client,id:'same',...o}));await handler(frame('client:a',{t:'request',method:'POST',path:'/api/agent-chat',bodyBytes:1}));await handler(frame('client:b',{t:'request',method:'POST',path:'/api/agent-chat',bodyBytes:1}));await handler(frame('client:a',{t:'upload',sequence:0,data:'YQ=='}));await handler(frame('client:b',{t:'upload',sequence:0,data:'Yg=='}));await handler(frame('client:a',{t:'cancel'}));assert.equal(active.size,1);await handler(frame('client:b',{t:'end'}));assert.deepEqual(bodies,['b']);assert.equal(events.at(-1).client,'client:b');assert.equal(active.size,0);});
test('disconnect and bridge error reject outstanding acknowledgment waiters',async t=>{for(const mode of ['disconnect','error']){const {w,sent,Socket}=await transport(t);const request=w.privateFetch('/api/agent-chat',{method:'POST',body:'pending'});await tick();if(mode==='disconnect')Socket.instance.close();else Socket.instance.receive({t:'error',id:sent[0].id,message:'not permitted'});await assert.rejects(request);await tick();assert.equal(sent.some(m=>m.t==='end'),false);}});
