"""Export helpers — JSON, LLM-readable agent context, and diff."""

from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path
from typing import Any

from .schema import CapabilityMap

AGENT_CONTEXT_PATH = Path.home() / ".hii" / "agent_context.md"


def as_json(cap: CapabilityMap, *, indent: int = 2) -> str:
    return json.dumps(cap.to_dict(), indent=indent, default=str)


# ── Agent-readable Markdown ────────────────────────────────────────────────

INTRO = """# HII Agent Context

HII (Human Information Interface) is your local-first capability registry and execution surface.
You — the AI agent — should treat this file as the authoritative, structured map of what this
machine can do, what is currently running, what files are available, and what safety rules apply.

This file is auto-generated by `hii caps refresh`. Treat older sections as cached; if you need
fresh information, ask the user to refresh.
"""


def _bullets(items: list, limit: int = 12) -> list[str]:
    out = []
    for i, c in enumerate(items[:limit]):
        marker = "✓" if c.available else "✗"
        version = f" v{c.version}" if c.version else ""
        endpoint = f" @ {c.endpoint}" if getattr(c, "endpoint", None) else ""
        path = f" ({c.path})" if c.path else ""
        out.append(f"- {marker} **{c.name}**{version}{endpoint}{path}  *[{c.confidence}, {c.detection_method}]*")
    if len(items) > limit:
        out.append(f"- … and {len(items) - limit} more")
    return out


def _model_bullets(models: list, limit: int = 25) -> list[str]:
    if not models:
        return ["- (none detected)"]
    # group by provider
    by_provider: dict[str, list] = {}
    for m in models:
        by_provider.setdefault(m.provider or "unknown", []).append(m)
    out = []
    for provider in sorted(by_provider):
        out.append(f"- **{provider}** ({len(by_provider[provider])} total)")
        for m in by_provider[provider][:8]:
            out.append(f"  - `{m.name}` *({m.model_type})*")
        if len(by_provider[provider]) > 8:
            out.append(f"  - … and {len(by_provider[provider]) - 8} more")
    return out


def as_llm(cap: CapabilityMap) -> str:
    lines: list[str] = [INTRO, ""]
    lines.append(f"_Last refresh: {cap.generated_at} (scan {cap.scan_id})_")
    lines.append("")

    # Host
    h = cap.host or {}
    lines.append("## Host")
    lines.append(
        f"- OS: {h.get('os')} {h.get('architecture')}\n"
        f"- User: {h.get('username')} @ {h.get('hostname')}\n"
        f"- Home: {h.get('home')}\n"
        f"- CWD: {h.get('cwd')}"
    )
    lines.append("")

    # Counts (one-line situational awareness)
    counts = cap.counts()
    lines.append("## At a glance")
    lines.append("  ".join(f"{k}: {v}" for k, v in counts.items()))
    lines.append("")

    # Runtime tools (skip the env_names dump)
    lines.append("## Runtime")
    lines.extend(_bullets([r for r in cap.runtime if r.id not in ("runtime.host", "runtime.env")]))
    lines.append("")

    # Apps
    lines.append("## Apps")
    lines.extend(_bullets(cap.apps, limit=25))
    lines.append("")

    # Services
    lines.append("## Services")
    lines.extend(_bullets(cap.services))
    lines.append("")

    # Models
    lines.append("## Models")
    lines.extend(_model_bullets(cap.models))
    lines.append("")

    # Workflows (just counts + a sample)
    lines.append("## Workflows")
    if cap.workflows:
        lines.append(f"- {len(cap.workflows)} workflow files indexed")
        for w in cap.workflows[:8]:
            lines.append(f"  - `{w.path}` ({w.file_extension})")
        if len(cap.workflows) > 8:
            lines.append(f"  - … and {len(cap.workflows) - 8} more")
    else:
        lines.append("- (none indexed)")
    lines.append("")

    # Assets
    lines.append("## Assets")
    if cap.assets:
        by_type: dict[str, int] = {}
        for a in cap.assets:
            by_type[a.media_type] = by_type.get(a.media_type, 0) + 1
        lines.append("- " + ", ".join(f"{k}: {v}" for k, v in sorted(by_type.items())))
    else:
        lines.append("- (none indexed)")
    lines.append("")

    # Allowed roots
    lines.append("## Allowed scan roots")
    for r in cap.allowed_roots:
        lines.append(f"- `{r}`")
    lines.append("")

    # Safety
    lines.append("## Safety rules")
    lines.append(
        "- Default tier is **read_only**; scripts (`.py/.bat/.ps1`) are **execute_confirm**; "
        "delete/move/overwrite operations are **destructive_confirm**.\n"
        "- Secret env values are never read, stored, or exported by capability scanners.\n"
        "- The agent must respect `permission_profile` on every capability before acting."
    )
    lines.append("")

    # Common commands
    lines.append("## Common HII commands")
    lines.append(
        "- `hii caps show` — pretty grouped summary\n"
        "- `hii caps refresh` — force rescan\n"
        "- `hii caps export --format llm` — this file\n"
        "- `hii caps export --format json` — full raw JSON\n"
        "- `hii caps diff` — compare current vs previous\n"
        "- `hii skill list|search|run` — skill registry"
    )
    lines.append("")

    # Warnings / errors (if any)
    if cap.warnings or cap.errors:
        lines.append("## Scan warnings & errors")
        for w in cap.warnings[:20]:
            lines.append(f"- warn: {w}")
        for e in cap.errors[:20]:
            lines.append(f"- err: {e}")
        if len(cap.warnings) > 20 or len(cap.errors) > 20:
            lines.append("- … truncated")
        lines.append("")

    return "\n".join(lines)


def write_agent_context(cap: CapabilityMap) -> Path:
    AGENT_CONTEXT_PATH.parent.mkdir(parents=True, exist_ok=True)
    AGENT_CONTEXT_PATH.write_text(as_llm(cap), encoding="utf-8")
    return AGENT_CONTEXT_PATH


# ── Diff (compact, human-readable) ─────────────────────────────────────────

def diff(current: dict[str, Any], previous: dict[str, Any]) -> dict[str, Any]:
    """Compare two CapabilityMap dicts. Returns added/removed/changed counts per kind."""
    out: dict[str, Any] = {}
    for kind in ("runtime", "apps", "services", "models", "workflows", "assets"):
        cur_ids = {c["id"]: c for c in current.get(kind, [])}
        prev_ids = {c["id"]: c for c in previous.get(kind, [])}
        added = sorted(cur_ids.keys() - prev_ids.keys())
        removed = sorted(prev_ids.keys() - cur_ids.keys())
        flipped = []
        for k in cur_ids.keys() & prev_ids.keys():
            if cur_ids[k].get("available") != prev_ids[k].get("available"):
                flipped.append(
                    f"{k}: {prev_ids[k].get('available')} → {cur_ids[k].get('available')}"
                )
        out[kind] = {
            "added": added[:20],
            "added_count": len(added),
            "removed": removed[:20],
            "removed_count": len(removed),
            "availability_flipped": flipped[:20],
            "flipped_count": len(flipped),
        }
    return out
