<script lang="ts">
  import { onMount } from 'svelte';
  import * as THREE from 'three';
  let canvas:HTMLCanvasElement, mode:'structure'|'shell'='structure', preset:'perspective'|'elevation'|'plan'='perspective', autoRotate=false, reference=false;
  let scene:THREE.Scene,camera:THREE.PerspectiveCamera,renderer:THREE.WebGLRenderer,model:THREE.Group,frame=0;
  const specs=[[-5.05,4.5,3.2,3.75],[-1.25,3.15,1.35,2.1],[3.35,7.65,3.05,3.7]];
  function rebuild(){if(!model)return;for(const child of [...model.children]){model.remove(child);(child as THREE.Mesh).geometry?.dispose();}for(const [x,w,h,d] of specs){const geometry=new THREE.SphereGeometry(1,32,18);geometry.scale(w/2,h/2,d/2);const shell=new THREE.Mesh(geometry,new THREE.MeshPhysicalMaterial({color:mode==='shell'?0xb9c7c2:0xd8e0dc,roughness:.45,transparent:true,opacity:mode==='shell'?.7:.13,side:THREE.DoubleSide}));shell.position.set(x,.55,0);model.add(shell);const wire=new THREE.LineSegments(new THREE.WireframeGeometry(geometry),new THREE.LineBasicMaterial({color:0x263330,transparent:true,opacity:.82}));wire.position.copy(shell.position);model.add(wire);}}
  function cameraPreset(){const p=preset==='plan'?[0,22,.01]:preset==='elevation'?[0,.8,21]:[12.5,7.2,14.5];camera.position.set(p[0],p[1],p[2]);camera.lookAt(0,0,0);}
  $: if(model){rebuild();cameraPreset();}
  onMount(()=>{scene=new THREE.Scene();scene.background=new THREE.Color(0xd7dcde);camera=new THREE.PerspectiveCamera(38,innerWidth/innerHeight,.1,80);renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);scene.add(new THREE.HemisphereLight(0xf5fbf8,0x7b8783,2));const light=new THREE.DirectionalLight(0xffffff,2.1);light.position.set(6,10,7);scene.add(light);model=new THREE.Group();scene.add(model);const floor=new THREE.Mesh(new THREE.BoxGeometry(19,.18,7.4),new THREE.MeshStandardMaterial({color:0xb8bfbe}));floor.position.y=-1.25;scene.add(floor);rebuild();cameraPreset();let dragging=false,lastX=0,lastY=0;const down=(e:PointerEvent)=>{dragging=true;lastX=e.clientX;lastY=e.clientY};const move=(e:PointerEvent)=>{if(!dragging)return;model.rotation.y+=(e.clientX-lastX)*.006;model.rotation.x+=(e.clientY-lastY)*.004;lastX=e.clientX;lastY=e.clientY};const up=()=>dragging=false;canvas.addEventListener('pointerdown',down);window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);const render=()=>{if(autoRotate)model.rotation.y+=.003;renderer.render(scene,camera);frame=requestAnimationFrame(render)};render();return()=>{cancelAnimationFrame(frame);renderer.dispose();window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)}});
</script>
<svelte:head><title>Organic Bridge Study · HII</title><meta name="description" content="Interactive concept reconstruction from a single orthographic wireframe reference."/></svelte:head>
<main class="relative h-screen min-h-[420px] w-screen overflow-hidden bg-[#d7dcde] text-[#121817]"><canvas bind:this={canvas} class="absolute inset-0 h-full w-full" aria-label="Interactive organic bridge model"></canvas><div class="absolute left-5 top-5 max-w-sm rounded-xl bg-white/85 p-4 shadow-xl backdrop-blur"><p class="font-mono text-[10px] uppercase tracking-[.18em] text-neutral-500">HII reconstruction study</p><h1 class="mt-2 text-2xl font-semibold">Organic bridge</h1><p class="mt-2 text-sm text-neutral-600">Drag to orbit a structural interpretation rebuilt from the original wireframe reference.</p><div class="mt-4 flex flex-wrap gap-2">{#each ['perspective','elevation','plan'] as view}<button class="hii-secondary-action" class:bg-black={preset===view} class:text-white={preset===view} on:click={()=>preset=view as typeof preset}>{view}</button>{/each}</div><div class="mt-2 flex gap-2"><button class="hii-secondary-action" on:click={()=>mode=mode==='shell'?'structure':'shell'}>{mode}</button><button class="hii-secondary-action" on:click={()=>autoRotate=!autoRotate}>{autoRotate?'pause':'rotate'}</button><button class="hii-secondary-action" on:click={()=>reference=!reference}>reference</button></div>{#if reference}<img class="mt-3 max-h-44 w-full object-contain" src="/api/workspace/assets/10077ca6-13b4-4e73-b642-f139e42810a0-Screenshot-2026-07-09-at-1.56.08-AM.png" alt="Original bridge wireframe reference"/>{/if}</div></main>
