<script lang="ts">
  import type { WorkspaceNode } from '@/lib/workspace/types';
  import { storeWorkspaceAsset } from '@/lib/workspace/ingest';
  export let node:WorkspaceNode; export let onPayload:(patch:Record<string,unknown>)=>void;
  type Message={id:string;role:'user'|'assistant';text:string;ts:string;status?:string;runId?:string;attachments?:any[]};
  let messages:Message[]=Array.isArray(node.payload.messages)?node.payload.messages as Message[]:[],draft='',attachments:any[]=[],busy=false,scroll:HTMLDivElement;
  function commit(next:Message[]){messages=next;onPayload({messages:next});setTimeout(()=>scroll?.scrollTo({top:scroll.scrollHeight}),0)}
  async function files(list:File[]){busy=true;attachments=[...attachments,...(await Promise.all(list.map(storeWorkspaceAsset))).filter(Boolean)];busy=false}
  async function poll(runId:string,assistantId:string){for(let attempt=0;attempt<240;attempt++){await new Promise(r=>setTimeout(r,1800));const response=await fetch(`/api/daemon/runs/${encodeURIComponent(runId)}`);if(!response.ok)break;const run=await response.json();const done=['completed','failed','stopped'].includes(run.status);commit(messages.map(item=>item.id===assistantId?{...item,status:run.status,text:run.status==='completed'?(String(run.output||'No response returned.').replace(/\x1b\[[0-9;?]*[ -/]*[@-~]/g,'').trim()):run.status==='running'?'Working locally…':run.status==='failed'?'The managed HII run failed.':'Queued with HII…'}:item));if(done)break}busy=false}
  async function send(){if(busy||(!draft.trim()&&!attachments.length))return;busy=true;const now=new Date().toISOString(),assistantId=crypto.randomUUID(),user:Message={id:crypto.randomUUID(),role:'user',text:draft.trim(),ts:now,attachments};const prompt=['You are responding inside the local HII workspace chat.','Answer clearly and concisely. Do not modify files or take external actions unless explicitly asked.',attachments.length?`Local attachments:\n${attachments.map(a=>`- ${a.path} (${a.mime})`).join('\n')}`:'',`User message:\n${draft.trim()||'Inspect the attached media.'}`].filter(Boolean).join('\n\n');commit([...messages,user,{id:assistantId,role:'assistant',text:'Queueing with HII…',ts:now,status:'queued'}]);draft='';attachments=[];try{const state=await (await fetch('/api/daemon')).json();if(!state.alive)await fetch('/api/daemon',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'start'})});const response=await fetch('/api/daemon',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'codex.run',prompt})}),data=await response.json();if(!response.ok||!data.result?.runId)throw new Error(data.error||'Could not queue chat');commit(messages.map(item=>item.id===assistantId?{...item,runId:data.result.runId}:item));void poll(data.result.runId,assistantId)}catch(error){commit(messages.map(item=>item.id===assistantId?{...item,status:'failed',text:error instanceof Error?error.message:'Could not start HII chat.'}:item));busy=false}}
</script>
<div class="flex h-full min-h-0 flex-col bg-[#fbfbfa]"><div bind:this={scroll} class="scroll min-h-0 flex-1 space-y-3 overflow-auto p-4">{#if !messages.length}<div class="mx-auto mt-16 max-w-[260px] text-center"><strong class="text-xl">Think with the workspace.</strong><p class="mt-2 text-xs text-neutral-500">Type a question or paste media. Send queues an inspectable Codex run.</p></div>{/if}{#each messages as message}<div class={message.role==='user'?'ml-8 rounded-2xl rounded-br-md bg-neutral-900 p-3 text-white':'mr-4 p-2'}>{#if message.attachments?.length}<div class="mb-2 font-mono text-[9px]">{message.attachments.map(a=>a.name).join(' · ')}</div>{/if}<pre class="whitespace-pre-wrap font-sans text-xs leading-relaxed">{message.text}</pre>{#if message.status&&message.status!=='completed'}<small class="font-mono uppercase opacity-50">{message.status}</small>{/if}</div>{/each}</div><div class="border-t bg-white p-3">{#if attachments.length}<div class="mb-2 flex gap-1">{#each attachments as attachment}<button class="rounded-full bg-neutral-100 px-2 text-[9px]" on:click={()=>attachments=attachments.filter(a=>a.path!==attachment.path)}>{attachment.name} ×</button>{/each}</div>{/if}<textarea bind:value={draft} on:keydown={(e)=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} class="h-20 w-full resize-none bg-transparent text-xs outline-none" placeholder="Message HII or paste media…"></textarea><div class="flex justify-between"><label class="cursor-pointer text-[10px]">+ media<input type="file" multiple class="sr-only" on:change={(e)=>files([...(e.currentTarget.files||[])])}/></label><button class="rounded-full bg-[var(--hii-electric-blue)] px-3 py-1.5 font-mono text-[10px] text-white disabled:opacity-30" disabled={busy||(!draft.trim()&&!attachments.length)} on:click={send}>{busy?'working…':'send to Codex ↵'}</button></div></div></div>
