//! Stable identity for Rhino and Grasshopper state.
//!
//! Nothing here identifies state by filename, window title, or "the active
//! document". A Rhino workstation can run several Rhino processes, each with
//! several open documents, and HII must never act on the wrong one.
//!
//! The rule for objects: `RhinoObject.Id` (a GUID) is the primary reference.
//! `RhinoObject.RuntimeSerialNumber` is kept only as a change stamp, because it
//! is reassigned when an object is replaced and would silently retarget.

use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Identifies one running HII Rhino bridge. Generated by the plug-in at load
/// and stable for that plug-in's lifetime, so a Rhino restart yields a new id
/// even when the OS reuses the process id.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct RhinoInstanceId(pub Uuid);

impl RhinoInstanceId {
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }
}

impl Default for RhinoInstanceId {
    fn default() -> Self {
        Self::new()
    }
}

impl std::fmt::Display for RhinoInstanceId {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(formatter, "{}", self.0)
    }
}

/// `RhinoDoc.RuntimeSerialNumber`. Unique per open document within one Rhino
/// process; it does not survive a restart, which is why it is always paired
/// with the instance id.
pub type DocumentRuntimeSerial = u32;

/// A Rhino document inside a specific bridge instance.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct DocumentRef {
    pub rhino_instance_id: RhinoInstanceId,
    pub document_runtime_serial: DocumentRuntimeSerial,
}

/// A Rhino session: one bridge instance, optionally narrowed to one document.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RhinoSessionRef {
    pub rhino_instance_id: RhinoInstanceId,
    pub process_id: u32,
    /// Windows logon session. Needed to rebuild the pipe name when
    /// reconnecting to an instance found through discovery.
    pub session_id: u32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub document_runtime_serial: Option<DocumentRuntimeSerial>,
}

/// A persistent Rhino object.
///
/// `object_id` is authoritative. `runtime_serial` is advisory: when the bridge
/// reports a different serial for the same GUID, the object was replaced since
/// the reference was minted, which callers may treat as a change signal.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RhinoObjectRef {
    pub rhino_instance_id: RhinoInstanceId,
    pub document_runtime_serial: DocumentRuntimeSerial,
    pub object_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub runtime_serial: Option<u32>,
}

impl RhinoObjectRef {
    pub fn document(&self) -> DocumentRef {
        DocumentRef {
            rhino_instance_id: self.rhino_instance_id.clone(),
            document_runtime_serial: self.document_runtime_serial,
        }
    }

    /// Same object, ignoring the advisory change stamp.
    pub fn same_object(&self, other: &Self) -> bool {
        self.rhino_instance_id == other.rhino_instance_id
            && self.document_runtime_serial == other.document_runtime_serial
            && self.object_id == other.object_id
    }
}

/// A Grasshopper document, identified by `GH_Document.RuntimeID`.
///
/// Grasshopper's own document server is the authority for which documents
/// exist; the active canvas is a UI detail and is deliberately not part of
/// identity.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct GrasshopperDocumentRef {
    pub rhino_instance_id: RhinoInstanceId,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rhino_document_runtime_serial: Option<DocumentRuntimeSerial>,
    pub gh_runtime_id: Uuid,
}

/// A Grasshopper document object (component, parameter, slider, ...).
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct GrasshopperObjectRef {
    pub gh_runtime_id: Uuid,
    pub instance_guid: Uuid,
}

/// What a request is addressed to. Requests that discover state (listing
/// sessions, for instance) carry no target at all.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum TargetRef {
    Instance { rhino_instance_id: RhinoInstanceId },
    Document(DocumentRef),
    GrasshopperDocument(GrasshopperDocumentRef),
}
