<script lang="ts">
  import { onMount } from 'svelte';
  type Currency='usd'|'eur'|'gbp'|'credits';
  let currency:Currency='usd', task='Use my computer to inspect the HII console, summarize what happened, and produce a demo-safe next action list.', budget=15, capabilityId='hii.agent.spawn', account:any=null, quote:any=null, capabilities:any[] = [], loading='', message='';
  const symbol:Record<Currency,string>={usd:'$',eur:'€',gbp:'£',credits:'cr '};
  const money=(c:number,unit:Currency=currency)=>unit==='credits'?`${Math.round(c/100)} credits`:`${symbol[unit]}${(c/100).toFixed(2)}`;
  async function load(){message=''; try{const [a,c]=await Promise.all([fetch(`/api/credits/account?currency=${currency}`),fetch('/api/capabilities')]);account=a.ok?await a.json():null; capabilities=c.ok?(await c.json()).capabilities??[]:[];}catch{account=null;}}
  async function request(endpoint:string,body:any){loading=endpoint;message='';try{const res=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),data=await res.json();if(!res.ok)throw new Error(data.error??'Request failed.');quote=data.quote??quote;message=data.job?`Reserved ${money(data.quote.totalCents,data.quote.currency)} for job ${data.job.id.slice(0,8)}.`:'Quote ready.';await load();}catch(error){message=error instanceof Error?error.message:'Request failed.'}finally{loading='';}}
  async function topUp(amountCents:number){const res=await fetch('/api/credits/checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({currency,amountCents})}),data=await res.json();if(res.ok)location.href=data.url;else message=data.error??'Checkout failed.';}
  onMount(load);
  $: active=quote??{id:'hii-preview',capabilityId,estimatedTokens:0,estimatedMinutes:0,totalCents:0,currency,status:'ready',transcript:[{actor:'user',text:task},{actor:'hii',text:'Send this as a task request. HII turns it into a quote, credit reservation, execution transcript, proof, and cost ledger.'}]};
</script>
<div class="hii-page"><section class="hii-page-header"><p class="hii-kicker">HII credits</p><h1 class="hii-page-title">Account balance, task quotes, receipts, and proof in one transcript.</h1><p class="hii-page-copy">Buy prepaid balance, reserve it for bounded capability work, then finalize each job into compute reimbursement, HII coordination fee, transcript, and proof artifacts.</p></section>
<section class="grid gap-5 pt-6 lg:grid-cols-[minmax(18rem,26rem)_1fr]"><aside class="space-y-5"><div class="hii-card"><h2 class="font-semibold">Account Balance</h2><label class="mt-4 block"><span class="text-sm text-neutral-600">Currency</span><select bind:value={currency} on:change={load} class="hii-select mt-1 w-full px-3 py-2"><option value="usd">USD</option><option value="eur">EUR</option><option value="gbp">GBP</option><option value="credits">HII credits</option></select></label><div class="mt-4 grid grid-cols-3 gap-3">{#each [['balance',account?.account?.balance_cents??0],['reserved',account?.account?.reserved_cents??0],['available',(account?.account?.balance_cents??0)-(account?.account?.reserved_cents??0)]] as item}<div class="hii-stat-card"><p class="text-xs uppercase text-neutral-500">{item[0]}</p><p class="mt-1 font-semibold">{money(Number(item[1]))}</p></div>{/each}</div>{#if currency!=='credits'}<div class="mt-4 grid grid-cols-2 gap-2">{#each [1000,2500,5000,10000] as amount}<button on:click={()=>topUp(amount)} class="hii-secondary-action">Add {money(amount)}</button>{/each}</div>{/if}</div>
<div class="hii-card"><h2 class="font-semibold">Task Request</h2><label class="mt-4 block"><span class="text-sm text-neutral-600">What should HII do?</span><textarea bind:value={task} class="hii-textarea mt-1 min-h-36 w-full px-3 py-2 text-sm"></textarea></label><label class="mt-3 block"><span class="text-sm text-neutral-600">Capability</span><select bind:value={capabilityId} class="hii-select mt-1 w-full px-3 py-2"><option value="hii.agent.spawn">Spawn bounded agent session</option>{#each capabilities as capability}<option value={capability.id}>{capability.name} ({capability.status})</option>{/each}</select></label><label class="mt-3 block"><span class="text-sm text-neutral-600">Max budget</span><input type="number" min="1" bind:value={budget} class="hii-field mt-1 w-full px-3 py-2"/></label><div class="mt-3 grid grid-cols-2 gap-2"><button class="hii-secondary-action" on:click={()=>request('/api/credits/quote',{task,currency,maxBudgetCents:budget*100,capabilityId})}>{loading.includes('quote')?'Quoting…':'Quote'}</button><button class="hii-command-button" on:click={()=>request('/api/capabilities/jobs',{task,currency,maxBudgetCents:budget*100,capabilityId})}>{loading.includes('jobs')?'Reserving…':'Reserve'}</button></div>{#if message}<p class="mt-3 text-sm">{message}</p>{/if}</div></aside>
<div class="space-y-5"><div class="grid gap-3 md:grid-cols-4">{#each [['status',active.status],['tokens',active.estimatedTokens],['runtime',`${active.estimatedMinutes} min`],['total',money(active.totalCents,active.currency)]] as stat}<div class="hii-stat-card"><p class="text-xs uppercase text-neutral-500">{stat[0]}</p><p class="mt-2 font-semibold">{stat[1]}</p></div>{/each}</div><div class="hii-terminal-frame"><div class="hii-terminal-bar"><span>hii://conversation/{active.id}</span><span>{active.capabilityId}</span></div><div class="space-y-3 p-4">{#each active.transcript??[] as turn}<div class="rounded border border-neutral-800 bg-neutral-950 p-3 text-green-100"><p class="font-mono text-xs uppercase text-neutral-400">{turn.actor}</p><p class="mt-2 text-sm leading-6">{turn.text}</p></div>{/each}</div></div><section class="hii-card"><h2 class="font-semibold">Recent Jobs</h2>{#each account?.jobs??[] as job}<div class="border-t py-3 text-sm"><p class="font-mono text-xs">{job.id}</p><p>{job.input_summary}</p><small>{job.capability_id} · {job.status} · {money(job.reserved_cents,job.currency)}</small></div>{:else}<p class="mt-4 text-neutral-500">No reserved jobs yet.</p>{/each}</section><section class="hii-card"><h2 class="font-semibold">Ledger</h2>{#each account?.ledger??[] as entry}<div class="grid grid-cols-[1fr_auto] border-t py-2 text-sm"><span>{entry.summary}</span><span class="font-mono">{money(entry.amount_cents??0,entry.currency)}</span></div>{:else}<p class="mt-4 text-neutral-500">No ledger rows yet.</p>{/each}</section></div></section></div>
